# Auto‑generated by generate_analysis
from pathlib import Path
CSV_PATH = Path(r"/Volumes/移动硬盘/Projects/EV/结题分析/2025数据/加工数据/成都_合并结果_20250814_114243.csv")

# Auto‑generated by generate_analysis

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# Load the dataset
try:
    data = pd.read_csv(CSV_PATH)
except FileNotFoundError:
    print("Dataset not found at the specified path.")
    exit()

# Visualization 1: Energy Consumption Patterns Across Different Time Periods
try:
    # Prepare data
    energy_columns = [
        "峰电量（kwh）_总和_当前值",
        "平电量（kwh）_总和_当前值",
        "谷电量（kwh）_总和_当前值"
    ]
    energy_data = data[energy_columns].sum()

    # Plot
    plt.figure(figsize=(8, 6))
    energy_data.plot(kind='bar', color=['#1f77b4', '#ff7f0e', '#2ca02c'])
    plt.title("Energy Consumption Across Time Periods", fontsize=14)
    plt.ylabel("Energy Consumption (kWh)", fontsize=12)
    plt.xlabel("Time Periods", fontsize=12)
    plt.xticks(ticks=np.arange(len(energy_columns)), labels=["Peak", "Flat", "Valley"], rotation=0, fontsize=10)
    plt.yticks(fontsize=10)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig("figures/energy_consumption_patterns.png")
    plt.show()
except KeyError as e:
    print(f"KeyError: {e} - Ensure the required columns exist in the dataset.")
except ValueError as e:
    print(f"ValueError: {e} - Check data values for inconsistencies.")
except TypeError as e:
    print(f"TypeError: {e} - Verify data types are correct for plotting.")

# Visualization 2: Order Channel Performance Analysis
try:
    # Prepare data
    order_channel_columns = [
        "订单渠道_e充电微信小程序_数量_变化率",
        "订单渠道_e充电Android_数量_变化率",
        "订单渠道_e充电ios_数量_变化率",
        "订单渠道_e充电支付宝小程序_数量_变化率"
    ]
    order_channel_data = data[order_channel_columns]

    # Rename columns for better readability
    order_channel_data.columns = [
        "WeChat Mini Program",
        "Android App",
        "iOS App",
        "Alipay Mini Program"
    ]

    # Plot
    plt.figure(figsize=(10, 6))
    order_channel_data.boxplot()
    plt.title("Order Channel Performance (Transaction Growth Rates)", fontsize=14)
    plt.ylabel("Growth Rate (%)", fontsize=12)
    plt.xlabel("Order Channels", fontsize=12)
    plt.xticks(fontsize=10)
    plt.yticks(fontsize=10)
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig("figures/order_channel_performance.png")
    plt.show()
except KeyError as e:
    print(f"KeyError: {e} - Ensure the required columns exist in the dataset.")
except ValueError as e:
    print(f"ValueError: {e} - Check data values for inconsistencies.")
except TypeError as e:
    print(f"TypeError: {e} - Verify data types are correct for plotting.")