# Auto‑generated by generate_analysis
from pathlib import Path
CSV_PATH = Path(r"/Volumes/移动硬盘/Projects/EV/结题分析/2025数据/加工数据/成都_合并结果_20250814_114243.csv")

# Auto‑generated by generate_analysis

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

# Load the dataset
try:
    df = pd.read_csv(CSV_PATH)
except FileNotFoundError:
    print("Dataset not found at the specified path.")
    exit()

# Ensure output directory exists
output_dir = Path("figures")
output_dir.mkdir(exist_ok=True)

# 1. Grouped Bar Chart: Order Channel Utilization
try:
    order_channels = [
        "订单渠道_e充电微信小程序_数量_当前值",
        "订单渠道_e充电微信小程序_数量_对比值",
        "订单渠道_e充电Android_数量_当前值",
        "订单渠道_e充电Android_数量_对比值",
        "订单渠道_e充电ios_数量_当前值",
        "订单渠道_e充电ios_数量_对比值",
        "订单渠道_e充电支付宝小程序_数量_当前值",
        "订单渠道_e充电支付宝小程序_数量_对比值",
    ]
    order_data = df[order_channels].sum()
    current_values = order_data[order_data.index.str.contains("当前值")]
    previous_values = order_data[order_data.index.str.contains("对比值")]

    x = np.arange(len(current_values))
    width = 0.35

    fig, ax = plt.subplots()
    ax.bar(x - width/2, current_values, width, label='Current')
    ax.bar(x + width/2, previous_values, width, label='Previous')

    ax.set_xticks(x)
    ax.set_xticklabels(['WeChat Mini', 'Android', 'iOS', 'Alipay'], rotation=45)
    ax.set_ylabel('Transaction Count')
    ax.set_title('Order Channel Utilization: Current vs Previous')
    ax.legend(title='Time Period')
    plt.tight_layout()
    plt.savefig(output_dir / "order_channel_utilization.png")
    plt.show()
except (KeyError, ValueError, TypeError) as e:
    print(f"Warning: Could not create Order Channel Utilization chart. {e}")

# 2. Line Chart: Energy Consumption Patterns
try:
    energy_columns = [
        "谷电量（kwh）_总和_当前值", "谷电量（kwh）_总和_对比值",
        "峰电量（kwh）_总和_当前值", "峰电量（kwh）_总和_对比值",
        "平电量（kwh）_总和_当前值", "平电量（kwh）_总和_对比值"
    ]
    energy_data = df[energy_columns].sum()
    categories = ['Valley Current', 'Valley Previous', 'Peak Current', 'Peak Previous', 'Flat Current', 'Flat Previous']

    fig, ax = plt.subplots()
    ax.plot(categories[:2], energy_data[:2], label='Valley Energy', marker='o')
    ax.plot(categories[2:4], energy_data[2:4], label='Peak Energy', marker='o')
    ax.plot(categories[4:], energy_data[4:], label='Flat Energy', marker='o')

    ax.set_ylabel('Energy Consumption (kWh)')
    ax.set_title('Energy Consumption Patterns (Current vs Previous)')
    ax.legend()
    plt.tight_layout()
    plt.savefig(output_dir / "energy_consumption_patterns.png")
    plt.show()
except (KeyError, ValueError, TypeError) as e:
    print(f"Warning: Could not create Energy Consumption Patterns chart. {e}")

# 3. Pie Chart: Geographic Distribution of Charging Stations
try:
    region_counts = df['所属区域'].value_counts()

    fig, ax = plt.subplots()
    ax.pie(region_counts, labels=region_counts.index, autopct='%1.1f%%', startangle=90, cmap=plt.cm.Paired)
    ax.set_title('Geographic Distribution of Charging Stations')
    plt.axis('equal')
    plt.tight_layout()
    plt.savefig(output_dir / "geographic_distribution.png")
    plt.show()
except (KeyError, ValueError, TypeError) as e:
    print(f"Warning: Could not create Geographic Distribution chart. {e}")

# 4. Bar Chart: Parking Fee Impact
try:
    parking_fee_counts = df['停车费类型'].value_counts()

    fig, ax = plt.subplots()
    ax.bar(parking_fee_counts.index, parking_fee_counts, color=plt.cm.Paired.colors)
    ax.set_ylabel('Number of Stations')
    ax.set_title('Impact of Parking Fees on Station Availability')
    ax.set_xticklabels(parking_fee_counts.index, rotation=45)
    plt.tight_layout()
    plt.savefig(output_dir / "parking_fee_impact.png")
    plt.show()
except (KeyError, ValueError, TypeError) as e:
    print(f"Warning: Could not create Parking Fee Impact chart. {e}")